packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
  - sharp
catalogMode: prefer
saveCatalog: true
catalog:
  "@eslint/js": ^9.29.0
  "@jest/globals": ^29.7.0
  "@next/eslint-plugin-next": ^15.3.0
  "@remix-run/dev": ^2.15.2
  "@remix-run/node": ^2.15.2
  "@remix-run/react": ^2.15.2
  "@remix-run/server-runtime": ^2.15.2
  "@types/body-parser": ^1.19.5
  "@types/cors": ^2.8.17
  "@types/express": 4.17.21
  "@types/morgan": ^1.9.9
  "@types/node": ^22.15.3
  "@types/supertest": ^6.0.2
  "@typescript-eslint/eslint-plugin": ^8.34.0
  "@typescript-eslint/parser": ^8.34.0
  "@vercel/analytics": ^1.5.0
  "@vercel/remix": 2.16.6
  "@vitejs/plugin-react": ^4.5.1
  autoprefixer: ^10.4.20
  body-parser: ^1.20.3
  bunchee: ^6.4.0
  cors: ^2.8.5
  eslint: ^9.29.0
  eslint-config-prettier: ^10.1.1
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-turbo: ^2.5.0
  express: 4.21.2
  globals: ^16.2.0
  isbot: ^5.1.23
  jest: ^29.7.0
  jest-environment-jsdom: ^29.7.0
  morgan: ^1.10.0
  next: ^15.3.0
  prettier: ^3.5.3
  react: ^18.3.1
  react-dom: ^18.3.1
  supertest: ^7.1.0
  ts-jest: ^29.4.0
  tsup: ^8.5.0
  turbo: ^2.5.4
  typescript-eslint: ^8.34.0
  vite: ^5.4.14
  vite-tsconfig-paths: 4.2.1
