# https://www.jetify.com/docs/devbox/guides/services/#defining-your-own-services
processes:
  api:
    depends_on:
      caddy:
      logger:
    command: "pnpm dev"
    namespace: "apps"
    working_dir: "apps/api"
    ready_log_line: "running"

  admin:
    depends_on:
      caddy:
      ui:
    command: "pnpm dev"
    namespace: "apps"
    working_dir: "apps/admin"
    ready_log_line: "localhost"

  blog:
    depends_on:
      caddy:
      ui:
    command: "pnpm dev"
    namespace: "apps"
    working_dir: "apps/blog"
    ready_log_line: "localhost"

  logger:
    command: "pnpm dev"
    namespace: "packages"
    working_dir: "packages/logger"
    ready_log_line: "Built"

  storefront:
    depends_on:
      api:
        condition: process_log_ready
      caddy:
      logger:
      ui:
    command: "pnpm dev"
    namespace: "apps"
    working_dir: "apps/storefront"
    ready_log_line: "Ready"

  ui:
    command: "pnpm dev"
    namespace: "packages"
    working_dir: "packages/ui"
    ready_log_line: "Built"
