name: Testing with devbox

on: push

jobs:
  devbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # https://turborepo.com/docs/guides/ci-vendors/github-actions#caching-with-github-actionscache
      - uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      # https://github.com/marketplace/actions/devbox-installer
      - uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: true

      - name: ${{ matrix.script }}
        run: devbox run turbo ${{ matrix.script }}
    strategy:
      matrix:
        script: ["check-types", "lint", "test"]
