name: Testing with devbox

on: push

jobs:
  devbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: true
      - name: ${{ matrix.script }}
        run: devbox run ${{ matrix.script }}
    strategy:
      matrix:
        script: ["check-types", "lint", "test"]
