name: Testing with devbox

on: push

jobs:
  devbox:
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v31
      - uses: actions/cache@v4
        with:
          path: "/home/runner/.local/share/pnpm/store/v10"
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - uses: jetify-com/devbox-install-action@v0.12.0
        with:
          devbox-version: 0.14.2
          enable-cache: true
          skip-nix-installation: true
      - name: ${{ matrix.script }}
        run: devbox run turbo ${{ matrix.script }}
      - run: devbox run --quiet pnpm store path
    strategy:
      matrix:
        script: ["check-types", "lint", "test"]
